name: PulseAudio Meter
version: "1.0.8"
slug: pulse_audio_meter
description: Live PulseAudio input/output meter with PulseAudio volume and mute controls
arch:
  - aarch64
  - amd64
audio: true
init: false
startup: services
boot: auto

map:
  - type: homeassistant_config
    read_only: false

ports:
  8765/tcp: 8765
ports_description:
  8765/tcp: Internal audio meter API
panel_icon: mdi:audio-video
